name: MyPy & Black

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy black
    - name: Analysing the code with mypy
      run: |
        mypy `ls -R|grep .py$|xargs`
    - name: Analysing the code with black
      run: |
        black --check `ls -R|grep .py$|xargs`
